### ISSUE TITLE
WIP Milestone version

### ISSUE THREAD

**Issue by simonrand** [wooga/gitthello#4]
I've no idea if you've any interest, or if there's even any reasonable way to merge the code, but I've refactored your code (thanks for the work on it!) to sync GitHub Milestones instead of issues, it also adds some more features like adding the milestone open/total issue count to the title of the card, combines counts on all cards related to a parent card..

While it might not be worth merging the functionality at some point, would be interested to share findings, potentially around figuring out why the Trello API seems so flaky?

Anyway, WIP code is here if you're interested: https://github.com/simonrand/gitthello/tree/milestones

[Trello Card](https://trello.com/c/1TH0ChuH/948-gitthello-wip-milestone-version)

**Comment by gorenje** [comment]
Not sure how milestones work (don't us them), so I might be off the mark here. If only milestones are sync'ed and not issues, then won't all issues need to be grouped into milestones to appear in trello?

It seems such a fundamental change that it would be better if there was a configuration to switch to select either issue sync'ing or milestone sync'ing. The projects I'm using gitthello with don't use milestones, so I (for one) would have to move everything to milestones.

**Comment by simonrand** [comment]
Was more a general query to see if this might be something you'd be interested in, I would suggest we keep things separate for now.

Any idea how to better debug Trello API calls that just return `ERROR`?
